import type { Section, Student, Task, Progress } from '@/types';

export const mockSections: Section[] = [
  {
    id: '1',
    name: 'Computer Science 101',
    code: 'CS101-A',
    subject: 'Computer Science',
    schedule: 'MWF 9:00-10:30 AM',
    room: 'Room 301',
    studentCount: 32,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Data Structures',
    code: 'CS201-B',
    subject: 'Computer Science',
    schedule: 'TTh 1:00-2:30 PM',
    room: 'Room 205',
    studentCount: 28,
    createdAt: '2024-01-15',
  },
  {
    id: '3',
    name: 'Web Development',
    code: 'CS301-C',
    subject: 'Computer Science',
    schedule: 'MWF 2:00-3:30 PM',
    room: 'Lab 102',
    studentCount: 25,
    createdAt: '2024-01-15',
  },
];

export const mockStudents: Student[] = [
  {
    id: '1',
    firstName: 'Emma',
    lastName: 'Johnson',
    studentId: 'STU001',
    email: 'emma.johnson@university.edu',
    sectionId: '1',
    enrolledAt: '2024-01-20',
  },
  {
    id: '2',
    firstName: 'Liam',
    lastName: 'Smith',
    studentId: 'STU002',
    email: 'liam.smith@university.edu',
    sectionId: '1',
    enrolledAt: '2024-01-20',
  },
  {
    id: '3',
    firstName: 'Olivia',
    lastName: 'Williams',
    studentId: 'STU003',
    email: 'olivia.williams@university.edu',
    sectionId: '1',
    enrolledAt: '2024-01-20',
  },
  {
    id: '4',
    firstName: 'Noah',
    lastName: 'Brown',
    studentId: 'STU004',
    email: 'noah.brown@university.edu',
    sectionId: '2',
    enrolledAt: '2024-01-20',
  },
  {
    id: '5',
    firstName: 'Ava',
    lastName: 'Davis',
    studentId: 'STU005',
    email: 'ava.davis@university.edu',
    sectionId: '2',
    enrolledAt: '2024-01-20',
  },
];

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Introduction to Programming Assignment',
    description: 'Complete the basic programming exercises covering variables, loops, and conditionals.',
    sectionId: '1',
    difficulty: 'Easy',
    dueDate: '2024-02-15',
    createdAt: '2024-02-01',
    totalPoints: 100,
  },
  {
    id: '2',
    title: 'Data Structures Quiz',
    description: 'Quiz covering arrays, linked lists, and basic tree structures.',
    sectionId: '2',
    difficulty: 'Medium',
    dueDate: '2024-02-20',
    createdAt: '2024-02-05',
    totalPoints: 50,
  },
  {
    id: '3',
    title: 'Web Development Project',
    description: 'Build a responsive landing page using HTML, CSS, and JavaScript.',
    sectionId: '3',
    difficulty: 'Hard',
    dueDate: '2024-03-01',
    createdAt: '2024-02-10',
    totalPoints: 150,
  },
];

export const mockProgress: Progress[] = [
  {
    id: '1',
    studentId: '1',
    taskId: '1',
    status: 'Completed',
    score: 95,
    feedback: 'Excellent work! Clean code and good logic.',
    submittedAt: '2024-02-14',
    updatedAt: '2024-02-14',
  },
  {
    id: '2',
    studentId: '2',
    taskId: '1',
    status: 'In Progress',
    score: null,
    feedback: null,
    submittedAt: null,
    updatedAt: '2024-02-12',
  },
  {
    id: '3',
    studentId: '3',
    taskId: '1',
    status: 'Not Started',
    score: null,
    feedback: null,
    submittedAt: null,
    updatedAt: '2024-02-01',
  },
];